[phases.setup]
nixPkgs = ['...', 'php83', 'php83Extensions.mbstring', 'php83Extensions.pdo', 'php83Extensions.tokenizer', 'php83Extensions.xml', 'php83Extensions.pcntl', 'php83Extensions.curl', 'php83Extensions.fileinfo', 'php83Extensions.openssl']

[phases.install]
cmds = [
    'composer install --no-dev --optimize-autoloader --no-interaction',
    'php artisan config:clear',
    'php artisan cache:clear',
    'php artisan view:clear'
]

[start]
cmd = 'bash start.sh'
